---
title: "SNV Heatmap"
author: "Stacy Hung"
date: "February 19, 2018"
output: html_document
---

## Prepare files for signature analysis

```{r}
library(dplyr)
library(plyr)

# load mutations for final 30 (not including GZ197), which has not been filtered for effect
# without GZ222, GZ229
#mutations.part1 <- read.table("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/snv_indel_datasets/snvs_indels.final_30_minus_GZ222_and_GZ229.default_and_optimized.incl_silent.txt", sep = "\t", header = TRUE, fill = TRUE)
# additionally, without GZ310
mutations.part1 <- read.table("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/snv_indel_datasets/snvs_indels.30_final.default_and_optimized.incl_silent.txt", sep = "\t", header = TRUE, fill = TRUE)
# load mutations for GZ197
mutations.part2 <- read.table("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/snv_indel_datasets/t_v_me.all/snvs_indels.t_v_me.GZ197.OPTIMIZED_thresholds.txt", sep = "\t", header = TRUE, fill = TRUE)
# combine mutations
mutations <- rbind(mutations.part1, mutations.part2)
rm(mutations.part1)
rm(mutations.part2)

# map SnpEffect values to equivalent MAF Variant_Classification categories
# map the actual patient id using the tumor id since the normal has a separate id
# Note: we will arbitrarily map all "FRAME_SHIFT" mutations to a Frame_Shift_Del since there isn't an easy way to tell otherwise if the frameshift is an insertion or deletion
snpeff_effect.to.MAF_VarClass <- c(
                            "CODON_DELETION"="Frame_Shift_Del",
                            "CODON_INSERTION"="Frame_Shift_Ins",
                            "NON_SYNONYMOUS_CODING"="Missense_Mutation",
                            "NON_SYNONYMOUS_START"="Missense_Mutation",
                            "SPLICE_SITE_ACCEPTOR"="Splice_Site",
                            "SPLICE_SITE_DONOR"="Splice_Site",
                            "SPLICE_SITE_REGION"="Splice_Site",
                            "START_GAINED"="Translation_Start_Site",
                            "START_LOST"="Missense_Mutation",
                            "STOP_GAINED"="Nonsense_Mutation",
                            "STOP_LOST"="Nonstop_Mutation",
                            "CODON_CHANGE_PLUS_CODON_INSERTION"="Frame_Shift_Ins",
                            "CODON_CHANGE_PLUS_CODON_DELETION"="Frame_Shift_Del",
                            "SYNONYMOUS_CODING"="Silent",
                            "SYNONYMOUS_STOP"="Silent",
                            "EXON"="Targeted_Region",
                            "FRAME_SHIFT"="Frame_Shift_Del",
                            "UTR_3_PRIME" = "3'UTR",
                            "UTR_5_PRIME" = "5'UTR"
                            )
mutations$Variant_Classification <- revalue(mutations$effect, snpeff_effect.to.MAF_VarClass)

# add label for SNP or INS or DEL
mutations$type <- if_else(grepl("(DELETION|FRAME_SHIFT)", mutations$effect), 
                          "DEL", 
                          if_else(grepl("INSERTION", mutations$effect), "INS", "SNP"))

#type.to_MAF_type <- c("snp"="SNP", "indel"="DEL")
#mutations$type <- revalue(mutations$type, type.to_MAF_type)

# keep only the columns that are relevant to MAF generation
keeps <- c("gene", "tumor_id", "Variant_Classification", "type", "ref", "alt", "gt_tumor", "impact", "fun_class", 
           "transcript_id", "chr", "pos", "type")
mutations <- mutations[keeps]

# rename samples column to match MAF format
library(data.table)
setnames(mutations, "tumor_id", "Tumor_Sample_Barcode")
setnames(mutations, "type", "Variant_Type")
setnames(mutations, "ref", "Reference_Allele")
setnames(mutations, "chr", "Chromosome")
setnames(mutations, "pos", "Start_Position")
setnames(mutations, "gene", "Hugo_Symbol")

# remove "chr" (to meet requirements for Chromosome column)
mutations$Chromosome <- gsub("^chr", "", mutations$Chromosome)

# reorder columns:
keeps <- c("Hugo_Symbol", "Tumor_Sample_Barcode", "Variant_Classification", "Variant_Type",  
           "Chromosome", "Start_Position", "Reference_Allele", "alt", "gt_tumor",
           "impact", "fun_class", "transcript_id")
mutations <- mutations[keeps]

# fill in Tumor_Seq_Allele1 and Tumor_Seq_Allele2 columns using gt column
# if gt = "0/1", fill in Tumor_Seq_Allele1 as reference allele, otherwise (gt = 1/1), fill with alterante allele
mutations$Tumor_Seq_Allele1 <- if_else(mutations$gt == "0/1", 
                                              mutations$Reference_Allele, 
                                              mutations$alt)
mutations$Tumor_Seq_Allele2 <- mutations$alt
mutations$alt <- NULL
mutations$gt <- NULL

# fill in gene name as "UNKNOWN" when missing (these are likely mutations that fall just outside the gene)
mutations$gene <- as.character(mutations$Hugo_Symbol)
mutations$gene[mutations$Hugo_Symbol==""] <- "UNKNOWN"
mutations$gene <- as.factor(mutations$Hugo_Symbol)

# Calculate end position
mutations$End_Position <- mutations$Start_Position # default: SNP
# For insertions: start coord = end coord + 1 --> end coord = start coord - 1
mutations$End_Position <- ifelse(mutations$Variant_Type == "INS", 
                                     mutations$Start_Position - 1,
                                     mutations$End_Position)
# For deletions: end coord = start coord + length (deletion) - 1
#   length (deletion) ~ length (REF) - 1 --> end coord = start coord + length (REF) - 2
mutations$End_Position <- ifelse(mutations$Variant_Type == "DEL", 
                                     mutations$Start_Position + nchar(as.character(mutations$Reference_Allele)) - 2, 
                                     mutations$End_Position)

write.table(mutations, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.default_and_optimized.incl_silent_and_UTR.maf", sep = "\t", quote = FALSE, row.names = FALSE)
#write.table(mutations, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229_and_GZ310.default_and_optimized.incl_silent_and_UTR.maf", sep = "\t", quote = FALSE, row.names = FALSE)
```

## Generatino of EBV+ and EBV- datasets (based on inclusion of silent and UTR mutations)

```{r}
library(plyr)

mutations.df <- read.table("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.default_and_optimized.incl_silent_and_UTR.maf", sep = "\t", header = TRUE, fill = TRUE)

# read in EBV status for patients
clinical.data <- read.table("/Volumes/shung/projects/gzl_exomes/data/GZ_WES_cases-clinical_data.mapped.txt", sep = "\t", header = TRUE, fill = TRUE)

patient.to.EBER_status <- as.vector(clinical.data$EBER)
names(patient.to.EBER_status) <- as.vector(clinical.data$tumor_id2)

mutations.df$EBER_status <- revalue(mutations.df$Tumor_Sample_Barcode, patient.to.EBER_status)

# get mutations for EBV+ (1) and EBV- (0) cases
mutations.EBER_pos <- filter(mutations.df, mutations.df$EBER_status == "Positive")
mutations.EBER_neg <- filter(mutations.df, mutations.df$EBER_status == "Negative")

#write.table(mutations.EBER_pos, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229_and_GZ310.incl_silent_and_UTR.EBER_pos.maf", sep = "\t", quote = TRUE, row.names = FALSE)
#write.table(mutations.EBER_neg, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229_and_GZ310.incl_silent_and_UTR.EBER_neg.maf", sep = "\t", quote = FALSE, row.names = FALSE)
write.table(mutations.EBER_pos, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.incl_silent_and_UTR.EBER_pos.maf", sep = "\t", quote = TRUE, row.names = FALSE)
write.table(mutations.EBER_neg, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.incl_silent_and_UTR.EBER_neg.maf", sep = "\t", quote = FALSE, row.names = FALSE)

```

## The mutational signature analysis

```{r}
library(maftools)
library('NMF')

#Requires BSgenome object
#source("https://bioconductor.org/biocLite.R")
#biocLite("BSgenome.Hsapiens.UCSC.hg19")

library(BSgenome.Hsapiens.UCSC.hg19)

#############################
# mutations in EBV+ patients
#############################

# read in mutations for EBV+ patients
mutations.maf <- read.maf("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.incl_silent_and_UTR.EBER_pos.maf")

# first, extract adjacent bases to the mutated locus and classify them into 96 subsitution classes
laml.tnm.eber_pos <- trinucleotideMatrix(maf = mutations.maf, prefix = 'chr', add = TRUE, ignoreChr = "chr23", 
                                ref_genome = "BSgenome.Hsapiens.UCSC.hg19")

# write out results
write.table(laml.tnm.eber_pos, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_positive/trinucleotide_matrix.txt", sep = "\t")

# extractSignatures uses a non-negative matrix factorization to decompose m samples x 96 matrix into r signatures.
# NB: we are using a pContstant value of 1 here since without this, we will get an error
laml.sign.eber_pos <- extractSignatures(mat = laml.tnm.eber_pos, plotBestFitRes = FALSE, pConstant = 1)

#Using 3 as a best-fit rank based on decreasing cophenetic correlation coefficient.
#Comparing against experimentally validated 30 signatures.. (See http://cancer.sanger.ac.uk/cosmic/signatures for details.)
#Found Signature_1 most similar to validated Signature_5. Aetiology: Unknown [cosine-similarity: 0.728] 
#Found Signature_2 most similar to validated Signature_5. Aetiology: Unknown [cosine-similarity: 0.785] 
#Found Signature_3 most similar to validated Signature_5. Aetiology: Unknown [cosine-similarity: 0.762] 

write.table(laml.sign.eber_pos$signatures, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_positive/signatures.txt", sep = "\t", quote = FALSE)

write.table(laml.sign.eber_pos$contributions, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_positive/contributions.txt", sep = "\t", quote = FALSE)

write.table(laml.sign.eber_pos$coSineSimMat, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_positive/cosineSimMat.txt", sep = "\t", quote = FALSE)

# plot signatures
plotSignatures(laml.sign.eber_pos, title_size = 1.2)
plotSignatures(laml.sign.eber_pos, contributions = TRUE, font_size = 0.8, show_barcodes = FALSE)

library(pheatmap)
pheatmap::pheatmap(mat = laml.sign.eber_pos$coSineSimMat, cluster_rows = FALSE, 
                   main = "cosine similarity against validated signatures")

#############################
# mutations in EBV- patients
#############################

# read in mutations for EBV- patients
mutations.maf <- read.maf("/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/input/snvs_indels.30_minus_GZ222_and_GZ229.incl_silent_and_UTR.EBER_neg.maf")

# first, extract adjacent bases to the mutated locus and classify them into 96 subsitution classes
laml.tnm.eber_neg <- trinucleotideMatrix(maf = mutations.maf, prefix = 'chr', add = TRUE, ignoreChr = "chr23", 
                                ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
# write out results
write.table(laml.tnm.eber_neg, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_negative/trinucleotide_matrix.txt", sep = "\t")

# extractSignatures uses a non-negative matrix factorization to decompose m samples x 96 matrix into r signatures.
laml.sign.eber_neg <- extractSignatures(mat = laml.tnm.eber_neg, plotBestFitRes = FALSE)

#Using 3 as a best-fit rank based on decreasing cophenetic correlation coefficient.
#Comparing against experimentally validated 30 signatures.. (See http://cancer.sanger.ac.uk/cosmic/signatures for details.)
#Found Signature_1 most similar to validated Signature_1. Aetiology: spontaneous deamination of 5-methylcytosine [cosine-similarity: 0.915] 
#Found Signature_2 most similar to validated Signature_2. Aetiology: APOBEC Cytidine Deaminase (C>T) [cosine-similarity: 0.715] 
#Found Signature_3 most similar to validated Signature_5. Aetiology: Unknown [cosine-similarity: 0.739] 

write.table(laml.sign.eber_neg$signatures, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_negative/signatures.txt", sep = "\t", quote = FALSE)

write.table(laml.sign.eber_neg$contributions, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_negative/contributions.txt", sep = "\t", quote = FALSE)

write.table(laml.sign.eber_neg$coSineSimMat, "/Volumes/shung/projects/gzl_exomes/snv_analysis-20181127/signature_analysis/results/EBER_groups/EBER_negative/cosineSimMat.txt", sep = "\t", quote = FALSE)

# plot signatures
plotSignatures(laml.sign.eber_neg, title_size = 1.2)
plotSignatures(laml.sign.eber_neg, contributions = TRUE, font_size = 0.8, show_barcodes = TRUE)

library(pheatmap)
pheatmap::pheatmap(mat = laml.sign.eber_neg$coSineSimMat, cluster_rows = FALSE, 
                   main = "cosine similarity against validated signatures")

```

## Plot contributions of signatures (ggplot2 version)

```{r}
library(ggplot2)
library(tidyr)

data.contrib <- as.data.frame(t(laml.sign.eber_pos$contributions))
data.contrib$patient <- row.names(data.contrib)

# convert from wide to long
data.contrib.long <- gather(data.contrib, signature, contribution, Signature_1:Signature_3, factor_key = TRUE)

p <- ggplot() + 
  geom_bar(aes(y = contribution, x = patient, fill = signature), data = data.contrib.long, stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))

```

## MutationalPatterns - plot contribution of signatures based on number of mutations

## Apply MutationalPatterns pkg to GZL data

```{r}
#library(BSgenome)
library("BSgenome.Hsapiens.UCSC.hg19", character.only = TRUE)
#source("https://bioconductor.org/biocLite.R")
#biocLite("MutationalPatterns")
library(MutationalPatterns) 

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"

# NB: this is based on references when running R in Rogue
vcf_files <- list.files(path = "/data/projects/stacy/gzl_exomes/signature_analysis/input", pattern = "*.vcf", full.names = TRUE, all.files = TRUE)

sample_names <- c("176T", "99T", "GZ_BCC_08_T_LMD", "GZ_BCC_13_T_LMD", "GZ_BCC_20_T_LMD", "GZ_BCC_54_T_LMD", "GZ044T-merged", "GZ046T-merged", "GZ048T-merged", "GZ062T-merged", "GZ064T", "GZ068T-merged", "GZ092_TLMD_2", "GZ095_TLMD_2", "GZ116T", "GZ149TLMD", "GZ152T-merged", "GZ178T", "GZ180_FFPE", "GZ184TLMD", "GZ197_TLMD", "GZ230T", "GZ235T", "GZ267T-merged", "GZ294T", "GZ301T", "GZ310T", "GZ32TLMD", "GZ86TLMD")

vcf <- read_vcfs_as_granges(vcf_files = vcf_files, sample_names = sample_names, ref_genome)

### 96 mutational profile

mut_mat <- mut_matrix(vcf_list = vcf, ref_genome = ref_genome)

pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/plot_96_profile-all_samples-condensed.pdf") 
#plot_96_profile(mut_mat)
plot_96_profile(mut_mat,condensed = TRUE)
dev.off() 

### de novo mutational signature extraction using NMF

# first add a small pseudocount to mutation count matrix
mut_mat <- mut_mat + 0.0001

# use the NMF package to generate an estimate rank plot
library(NMF)
estimate <- nmf(mut_mat, rank = 2:5, method = "brunet", nrun = 10, seed = 123456) # doesn't work on Rogue

pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/plot_estimate.pdf") 
plot(estimate)
dev.off() 

# based on ranking survey plots, optimal rank is 3 (cophentic cofficient starts dropping and RSS inflects at 3)
# perform a relative large number iterations to achieve stability and avoid local minima
nmf_res <- extract_signatures(mut_mat, rank = 3, nrun = 100)

# assign signature names:
colnames(nmf_res$signatures) <- c("GZ Signature A", "GZ Signature B", "GZ Signature C")
rownames(nmf_res$contribution) <- c("GZ Signature A", "GZ Signature B", "GZ Signature C")

# plot the 96-profile of the signatures
pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/plot_96_profile.pdf") 
plot_96_profile(nmf_res$signatures, condensed = TRUE)
dev.off() 

# visualize the contribution of the signatures in a barplot
pc1 <- plot_contribution(nmf_res$contribution, nmf_res$signature, mode = "relative", coord_flip=TRUE)
# visualize the contribution in absolute number of mutations
pc2 <- plot_contribution(nmf_res$contribution, nmf_res$signature, mode = "absolute", coord_flip=TRUE)

# combine the two plots
library(gridExtra)
pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/signature-relative_and_absoluate_contributions.pdf") 
grid.arrange(pc1, pc2)
dev.off()

# Plot signature contribution as a heatmap with sample clustering dendogram and specified signature order:
pch1 <- plot_contribution_heatmap(nmf_res$contribution, sig_order = c("GZ Signature A", "GZ Signature B", "GZ Signature C"))
# plot signature contribution as a heatmap without sample clustering
pch2 <- plot_contribution_heatmap(nmf_res$contribution, cluster_samples=FALSE)

# combine plots into one figure
pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/signature-heatmap_contributions.pdf") 
grid.arrange(pch1, pch2)
dev.off()

# compare reconstructed mutational profile with original mutational profile
pdf("/data/projects/stacy/gzl_exomes/signature_analysis/figures/comparison_of_profiles.pdf") 
plot_compare_profiles(mut_mat[,1], nmf_res$reconstructed[,1], profile_names = c("Original", "Reconstructed"), condensed = TRUE)
dev.off()

## COSMIC mutational signatures


```



